name: thoroughio
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

  # sdk: ">=2.14.0 <3.0.0"
 # sdk: ">=2.16.0-80.1.beta <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
#  flutter_svg: ^1.0.3
  flutter_svg: ^0.22.0
  webview_flutter: ^2.0.9
  flutter_webview_plugin: ^0.4.0

  pin_code_fields: ^7.3.0
  dotted_border: ^2.0.0
  cached_network_image: ^3.2.0
  simple_timer: ^2.0.0
#  file_picker: ^4.4.0
#  image_picker: ^0.8.4+2
  permission_handler: ^8.1.3

  flutter_statusbarcolor: ^0.2.3
  http: ^0.13.3
  connectivity: ^3.0.6
  shared_preferences: ^2.0.6
#  fluttertoast: ^8.0.8
  intl: ^0.17.0
  webview_flutter_plus: ^0.2.2
  dots_indicator: ^2.1.0
#  circle_indicator: any
  page_view_indicators: ^2.0.0
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
   - assets/svgfiles/
   - assets/pngfiles/


     # fonts:
     #  - family: NotoBlack
     #    fonts:
     #     - asset: assets/font/NotoSans-Black.ttf
     #  - family: NotoBold
     #   fonts:
     #  - asset: assets/font/NotoSans-Bold.ttf
     #- family: NotoCondensedBold
     # fonts:
     #   - asset: assets/font/NotoSans-CondensedBold.ttf
     #- family: NotoCondensedLight
     #  fonts:
     #  - asset: assets/font/NotoSans-CondensedLight.ttf
     #- family: NotoCondensedMedium
     #  fonts:
     # - asset: assets/font/NotoSans-ExtraCondensedMedium.ttf
     #- family: NotoExtraCondensedSemiBold
     # fonts:
     #   - asset: assets/font/NotoSans-ExtraCondensedSemiBold.ttf
     #- family: NotoExtraCondensedThin
     # fonts:
     #   - asset: assets/font/NotoSans-ExtraCondensedThin.ttf
     #- family: NotoLight
     # fonts:
     #   - asset: assets/font/NotoSans-Light.ttf
     #- family: NotoMedium
     # fonts:
     #   - asset: assets/font/NotoSans-Medium.ttf
     #- family: NotoRegular
     #  fonts:
     #    - asset: assets/font/NotoSans-Regular.ttf
     #- family: NotoSemiBold
     # fonts:
     #   - asset: assets/font/NotoSans-SemiBold.ttf
     #- family: NotoThin
     # fonts:
    #   - asset: assets/font/NotoSans-Thin.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
